name: Deploy Next.js Blog

on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: deploy with ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.PATH }}
            git checkout -- app/tag-data.json
            git pull origin main
            pm2 delete nextjs-blog || true
            yarn
            yarn build
            pm2 start yarn --interpreter bash  --name "nextjs-blog" -- start
            pm2 save